apiVersion: 1

deleteDatasources:
  - name: WaveGuard Metrics
    orgId: 1

datasources:
  - name: WaveGuard Metrics
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: http://localhost:3000
    isDefault: true
    version: 1
    editable: true
    jsonData:
      global_queries: []
      allowed_hosts:
        - "localhost"
        - "127.0.0.1"
        - "host.docker.internal"
      auth_method: None
      oauth2_settings:
        type: None
      custom_http_headers:
        - name: "Cache-Control"
          value: "no-cache"
      default_parser: "json"
      default_format: "table"
      # ✅ Utiliser le chemin absolu vers le fichier
      url: "file:///tmp/metrics/waveguard_metrics.json"